
services:
  web:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - /home/lera/Projects/online-shop/Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/lera/Projects/online-shop:/var/www/html


  php-fpm:
    build: /home/lera/Projects/online-shop/Docker/php
    volumes:
      - /home/lera/Projects/online-shop:/var/www/html


  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "54322:5432"


